# Generated by Django 5.1 on 2026-05-13 22:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tour_price_dates_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='dates_display',
            field=models.CharField(blank=True, help_text='Текстовое описание выездных дат для сайта.', max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.JSONField(default=core.models.default_places),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_from_rub',
            field=models.PositiveIntegerField(default=0, help_text='Стоимость «от», руб. за человека (ориентир для лендинга).'),
        ),
    ]
